name: network_to_ui
description: "A Flutter package for simplified network requests and UI integration with Dio and BLoC."
version: 0.1.3
license: MIT
homepage:
repository: https://github.com/thurain11/network_to_ui_package

environment:
  sdk: ^3.5.4
  flutter: '>=2.0.0'


dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0
  get_it: ^8.0.3
  fluttertoast: ^8.2.12
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
